preprocessor.bin RenameElement hair_1_1.gr2 -output hair_1_1.gr2 -rename textures[0] -newname "d:\ymir work\pc2\sura\hair\hair_1_1.dds"
preprocessor.bin RenameElement hair_1_1.gr2 -output hair_1_2.gr2 -rename textures[0] -newname "d:\ymir work\pc2\sura\hair\hair_1_2.dds"
preprocessor.bin RenameElement hair_1_1.gr2 -output hair_1_3.gr2 -rename textures[0] -newname "d:\ymir work\pc2\sura\hair\hair_1_3.dds"
preprocessor.bin RenameElement hair_1_1.gr2 -output hair_1_4.gr2 -rename textures[0] -newname "d:\ymir work\pc2\sura\hair\hair_1_4.dds"
preprocessor.bin RenameElement hair_1_1.gr2 -output hair_1_5.gr2 -rename textures[0] -newname "d:\ymir work\pc2\sura\hair\hair_1_5.dds"
preprocessor.bin RenameElement hair_1_1.gr2 -output hair_1_6.gr2 -rename textures[0] -newname "d:\ymir work\pc2\sura\hair\hair_1_6.dds"
preprocessor.bin RenameElement hair_1_1.gr2 -output hair_1_7.gr2 -rename textures[0] -newname "d:\ymir work\pc2\sura\hair\hair_1_7.dds"
preprocessor.bin RenameElement hair_1_1.gr2 -output hair_1_8.gr2 -rename textures[0] -newname "d:\ymir work\pc2\sura\hair\hair_1_8.dds"
preprocessor.bin RenameElement hair_1_1.gr2 -output hair_1_9.gr2 -rename textures[0] -newname "d:\ymir work\pc2\sura\hair\hair_1_9.dds"
preprocessor.bin RenameElement hair_1_1.gr2 -output hair_1_10.gr2 -rename textures[0] -newname "d:\ymir work\pc2\sura\hair\hair_1_10.dds"
preprocessor.bin RenameElement hair_1_1.gr2 -output hair_1_11.gr2 -rename textures[0] -newname "d:\ymir work\pc2\sura\hair\hair_1_11.dds"
preprocessor.bin RenameElement hair_1_1.gr2 -output hair_1_12.gr2 -rename textures[0] -newname "d:\ymir work\pc2\sura\hair\hair_1_12.dds"

preprocessor.bin RenameElement hair_2_1.gr2 -output hair_2_1.gr2 -rename textures[0] -newname "d:\ymir work\pc2\sura\hair\hair_2_1.dds"
preprocessor.bin RenameElement hair_2_1.gr2 -output hair_2_2.gr2 -rename textures[0] -newname "d:\ymir work\pc2\sura\hair\hair_2_2.dds"
preprocessor.bin RenameElement hair_2_1.gr2 -output hair_2_3.gr2 -rename textures[0] -newname "d:\ymir work\pc2\sura\hair\hair_2_3.dds"
preprocessor.bin RenameElement hair_2_1.gr2 -output hair_2_4.gr2 -rename textures[0] -newname "d:\ymir work\pc2\sura\hair\hair_2_4.dds"
preprocessor.bin RenameElement hair_2_1.gr2 -output hair_2_5.gr2 -rename textures[0] -newname "d:\ymir work\pc2\sura\hair\hair_2_5.dds"
preprocessor.bin RenameElement hair_2_1.gr2 -output hair_2_6.gr2 -rename textures[0] -newname "d:\ymir work\pc2\sura\hair\hair_2_6.dds"
preprocessor.bin RenameElement hair_2_1.gr2 -output hair_2_7.gr2 -rename textures[0] -newname "d:\ymir work\pc2\sura\hair\hair_2_7.dds"
preprocessor.bin RenameElement hair_2_1.gr2 -output hair_2_8.gr2 -rename textures[0] -newname "d:\ymir work\pc2\sura\hair\hair_2_8.dds"
preprocessor.bin RenameElement hair_2_1.gr2 -output hair_2_9.gr2 -rename textures[0] -newname "d:\ymir work\pc2\sura\hair\hair_2_9.dds"
preprocessor.bin RenameElement hair_2_1.gr2 -output hair_2_10.gr2 -rename textures[0] -newname "d:\ymir work\pc2\sura\hair\hair_2_10.dds"
preprocessor.bin RenameElement hair_2_1.gr2 -output hair_2_11.gr2 -rename textures[0] -newname "d:\ymir work\pc2\sura\hair\hair_2_11.dds"
preprocessor.bin RenameElement hair_2_1.gr2 -output hair_2_12.gr2 -rename textures[0] -newname "d:\ymir work\pc2\sura\hair\hair_2_12.dds"

preprocessor.bin RenameElement hair_3_1.gr2 -output hair_3_1.gr2 -rename textures[0] -newname "d:\ymir work\pc2\sura\hair\hair_3_1.dds"
preprocessor.bin RenameElement hair_3_1.gr2 -output hair_3_2.gr2 -rename textures[0] -newname "d:\ymir work\pc2\sura\hair\hair_3_2.dds"
preprocessor.bin RenameElement hair_3_1.gr2 -output hair_3_3.gr2 -rename textures[0] -newname "d:\ymir work\pc2\sura\hair\hair_3_3.dds"
preprocessor.bin RenameElement hair_3_1.gr2 -output hair_3_4.gr2 -rename textures[0] -newname "d:\ymir work\pc2\sura\hair\hair_3_4.dds"
preprocessor.bin RenameElement hair_3_1.gr2 -output hair_3_5.gr2 -rename textures[0] -newname "d:\ymir work\pc2\sura\hair\hair_3_5.dds"
preprocessor.bin RenameElement hair_3_1.gr2 -output hair_3_6.gr2 -rename textures[0] -newname "d:\ymir work\pc2\sura\hair\hair_3_6.dds"
preprocessor.bin RenameElement hair_3_1.gr2 -output hair_3_7.gr2 -rename textures[0] -newname "d:\ymir work\pc2\sura\hair\hair_3_7.dds"
preprocessor.bin RenameElement hair_3_1.gr2 -output hair_3_8.gr2 -rename textures[0] -newname "d:\ymir work\pc2\sura\hair\hair_3_8.dds"
preprocessor.bin RenameElement hair_3_1.gr2 -output hair_3_9.gr2 -rename textures[0] -newname "d:\ymir work\pc2\sura\hair\hair_3_9.dds"
preprocessor.bin RenameElement hair_3_1.gr2 -output hair_3_10.gr2 -rename textures[0] -newname "d:\ymir work\pc2\sura\hair\hair_3_10.dds"
preprocessor.bin RenameElement hair_3_1.gr2 -output hair_3_11.gr2 -rename textures[0] -newname "d:\ymir work\pc2\sura\hair\hair_3_11.dds"
preprocessor.bin RenameElement hair_3_1.gr2 -output hair_3_12.gr2 -rename textures[0] -newname "d:\ymir work\pc2\sura\hair\hair_3_12.dds"

preprocessor.bin RenameElement hair_4_1.gr2 -output hair_4_1.gr2 -rename textures[0] -newname "d:\ymir work\pc2\sura\hair\hair_4_1.dds"
preprocessor.bin RenameElement hair_4_1.gr2 -output hair_4_2.gr2 -rename textures[0] -newname "d:\ymir work\pc2\sura\hair\hair_4_2.dds"
preprocessor.bin RenameElement hair_4_1.gr2 -output hair_4_3.gr2 -rename textures[0] -newname "d:\ymir work\pc2\sura\hair\hair_4_3.dds"
preprocessor.bin RenameElement hair_4_1.gr2 -output hair_4_4.gr2 -rename textures[0] -newname "d:\ymir work\pc2\sura\hair\hair_4_4.dds"
preprocessor.bin RenameElement hair_4_1.gr2 -output hair_4_5.gr2 -rename textures[0] -newname "d:\ymir work\pc2\sura\hair\hair_4_5.dds"
preprocessor.bin RenameElement hair_4_1.gr2 -output hair_4_6.gr2 -rename textures[0] -newname "d:\ymir work\pc2\sura\hair\hair_4_6.dds"
preprocessor.bin RenameElement hair_4_1.gr2 -output hair_4_7.gr2 -rename textures[0] -newname "d:\ymir work\pc2\sura\hair\hair_4_7.dds"
preprocessor.bin RenameElement hair_4_1.gr2 -output hair_4_8.gr2 -rename textures[0] -newname "d:\ymir work\pc2\sura\hair\hair_4_8.dds"
preprocessor.bin RenameElement hair_4_1.gr2 -output hair_4_9.gr2 -rename textures[0] -newname "d:\ymir work\pc2\sura\hair\hair_4_9.dds"
preprocessor.bin RenameElement hair_4_1.gr2 -output hair_4_10.gr2 -rename textures[0] -newname "d:\ymir work\pc2\sura\hair\hair_4_10.dds"
preprocessor.bin RenameElement hair_4_1.gr2 -output hair_4_11.gr2 -rename textures[0] -newname "d:\ymir work\pc2\sura\hair\hair_4_11.dds"
preprocessor.bin RenameElement hair_4_1.gr2 -output hair_4_12.gr2 -rename textures[0] -newname "d:\ymir work\pc2\sura\hair\hair_4_12.dds"

@pause