#favor manter essa linha
import grp
import enszxc3467hc3kokdueq as app
import colorinfo

LINE = "interface/controls/common/horizontal_bar/center.tga"
SLOT_BASE = "interface/controls/common/slot_ellipse/slot_vazio.tga"
SLOT = "interface/controls/common/slot_ellipse/slot.tga"
SLOT_BLOCK = "interface/controls/common/slot_ellipse/slot_lock1.tga"
QUEST_CLOSE = "interface/icons/special/quest_closed.tga"
QUEST_OPEN = "interface/icons/special/quest_open.tga"

width = 420
height = 426

box_color = colorinfo.COR_INPUT_BOX
normal_color = grp.GenerateColor(0.0, 0.0, 0.0, 1.0)
hover_color = grp.GenerateColor(0.1, 0.1, 0.1, 1.0)
hover_color2 = grp.GenerateColor(0.05, 0.05, 0.05, 1.0)
text_color = colorinfo.COR_TEXTO_PADRAO
color_quest = grp.GenerateColor(0.0, 0.0, 0.0, 0.2)

window = {
	"name":"CharacterWindow",
	"x":50,
	"y":(SCREEN_HEIGHT - 37 - 361) / 2,
	"style":("movable", "float",),
	"width":width,
	"height":height,
	"children":
	(
		{
			"name":"board",
			"type":"new_board_with_titlebar",
			"title":"Personagem",
			"style":("attach",),
			"x":0,
			"y":0,
			"width":width,
			"height":height,
			"children":
			(
				{
					"name":"vertical_separator",
					"type":"verticalseparator",
					"height":height - 45,
					"x":285,
					"y":38,
				},
				{
					"name":"horizontal_separator",
					"type":"horizontalseparator",
					"width":279,
					"x":7,
					"y":92,
				},
				{
					"name":"horizontal_separator",
					"type":"horizontalseparator",
					"width":279,
					"x":7,
					"y":140,
				},
				{
					"name":"Character_Name_Slot",
					"type": "barwithbox",
					"width":100, "height":18+11,
					"color": normal_color,
					"flash_color": box_color,
					"box_color": box_color,
					"x":72,
					"y":41,
					"children":
					(
						{"name":"Character_Name","type":"text","text":"Sem Nome","x":0,"y":-1,"color":text_color,"all_align":"center","style":("not_pick",),},
					),
				},
				{
					"name":"Guild_Name_Slot",
					"type": "barwithbox",
					"width":109, "height":18+11,
					"color": normal_color,
					"flash_color": hover_color,
					"box_color": box_color,
					"x":174,
					"y":41,
					"children":
					(
						{"name":"Guild_Name","type":"text","text":"Sem Guild","x":0,"y":-1,"color":text_color,"all_align":"center","style":("not_pick",),},
					),
				},
				{
					"name":"ExpImgEmpty",
					"type":"image",
					"x":55,
					"y":110-3,
					"image":"interface/controls/special/character/exp_gauge_empty.tga",
					"children":
					(
						{
							"name":"ExpImgFull",
							"type":"expanded_image",
							"x":0,
							"y":0,
							"image": "interface/controls/special/character/exp_gauge_full.tga",
						},
						{"name":"","type":"text","color":text_color,"text":"Próximo Nível","x":0,"y":-8,"horizontal_align":"center","text_horizontal_align":"center",},
						{"name":"Exp_Value","type":"text","color":text_color,"text":"999999 de 999999999","x":0,"y":15,"horizontal_align":"center","text_horizontal_align":"center",},
					),
				},
				{"name":"PercentExp","type":"text","color":text_color,"text":"100%","x":13,"y":110-3,"fontsize":"LARGE","outline":1,},
				{
					"name":"Face_Slot",
					"type": "barwithbox",
					"x":10, "y": 10+31,
					"width":60, "height":60-31,
					"color": normal_color,
					"flash_color": normal_color,
					"box_color": box_color,
					"children":
					(
						{"name":"Face_Image","type":"expanded_image","x":1,"y":-19-31,"image":"interface/controls/common/faces/warrior_m.tga",},
					)
				},
				{
					"name":"LevelSlot",
					"type": "barwithbox",
					"x":10,
					"y":72,
					"width":60, "height":18,
					"color": normal_color,
					"flash_color": hover_color,
					"box_color": box_color,
					"children":
					(
						{"name":"Level_Value","type":"text","text":"","x":0,"y":-1,"all_align":"center","color":text_color,},
					),
				},
				################ RANKING ##########################################
				{
					"name":"ranking_position_window",
					"type": "barwithbox",
					"color": normal_color,
					"flash_color": hover_color,
					"box_color": box_color,
					"x":72,
					"y":72,
					"height":18,
					"width":100,
					"children":
					(
						{"name":"ranking_position","type":"text","text":"1º Lugar","x":0,"y":-1,"color":0xfff8d090,"style":("not_pick",),"all_align":"center",},
					),
				},
				{
					"name":"ranking_position_window",
					"type": "barwithbox",
					"color": normal_color,
					"flash_color": hover_color,
					"box_color": box_color,
					"x":174,
					"y":72,
					"height":18,
					"width":109,
					"children":
					(
						{"name":"ranking_points","type":"text","text":"150 Pontos","x":0,"y":-1,"style":("not_pick",),"all_align":"center",},
					),
				},
#############################################################################################################################
				{
					"name":"Options",
					"type":"window",
					"x":width-130,
					"y":41,
					"width":130,
					"height":height-41,
					"children":
					(
						{
							"name":"Tab_Button_01",
							"type":"redbutton",
							"text":"Status",
							"width":119,
							"x":0,
							"y":0,
						},
						{
							"name":"Tab_Button_02",
							"type":"redbutton",
							"text":"Habilidades",
							"width":119,
							"x":0,
							"y":30*1,
						},
						{
							"name":"Tab_Button_03",
							"type":"redbutton",
							"text":"Emoções",
							"width":119,
							"x":0,
							"y":30*2,
						},
						{
							"name":"Tab_Button_04",
							"type":"redbutton",
							"text":"Quests",
							"width":119,
							"x":0,
							"y":30*3,
						},
						{
							"name":"Tab_Button_05",
							"type":"redbutton",
							"text":"Pág. de Bônus",
							"width":119,
							"x":0,
							"y":30*4,
						},
						{
							"name":"Tab_Button_06",
							"type":"redbutton",
							"text":"Classificação",
							"width":119,
							"x":0,
							"y":30*5,
						},
					),
				},
### PAGINA DE STATUS ###### PAGINA DE STATUS ###### PAGINA DE STATUS ###### PAGINA DE STATUS ###### PAGINA DE STATUS ###
				{
					"name":"Character_Page",
					"type":"window",
					"style":("attach",),
					"width":278,
					"height":282,
					"x":8,
					"y":141,
					"children":
					(
						{
							"name":"SlotHP",
							"type": "barwithbox",
							"color": normal_color,
							"flash_color": normal_color,
							"box_color": normal_color,
							"width":269,
							"height":23,
							"x":4,
							"y":5,
							"children":
							(
								{"name":"HP_Value","type":"text","text":"","x":5,"y":-1,"style":("not_pick",),"vertical_align":"center","text_vertical_align":"center",},
							),
						},
						{
							"name":"SlotMP",
							"type": "barwithbox",
							"color": normal_color,
							"flash_color": normal_color,
							"box_color": normal_color,
							"width":269,
							"height":23,
							"x":4,
							"y":5 + 25*1,
							"children":
							(
								{"name":"SP_Value","type":"text","text":"","x":5,"y":-1,"style":("not_pick",),"vertical_align":"center","text_vertical_align":"center",},
							),
						},
						{
							"name":"AttackValueBg",
							"type": "barwithbox",
							"color": normal_color,
							"flash_color": normal_color,
							"box_color": normal_color,
							"width":269,
							"height":23,
							"x":4,
							"y":5 + 25*2,
							"children":
							(
								{"name":"ATT_Value","type":"text","text":"","x":5,"y":-1,"style":("not_pick",),"vertical_align":"center","text_vertical_align":"center",},
							),
						},
						{
							"name":"MagicAttackValueBg",
							"type": "barwithbox",
							"color": normal_color,
							"flash_color": normal_color,
							"box_color": normal_color,
							"width":269,
							"height":23,
							"x":4,
							"y":5 + 25*3,
							"children":
							(
								{"name":"MATT_Value","type":"text","text":"","x":5,"y":-1,"style":("not_pick",),"vertical_align":"center","text_vertical_align":"center",},
							),
						},
						{
							"name":"MagicDefValueBg",
							"type": "barwithbox",
							"color": normal_color,
							"flash_color": normal_color,
							"box_color": normal_color,
							"width":269,
							"height":23,
							"x":4,
							"y":5 + 25*4,
							"children":
							(
								{"name":"MDEF_Value","type":"text","text":"","x":5,"y":-1,"style":("not_pick",),"vertical_align":"center","text_vertical_align":"center",},
							),
						},
						{
							"name":"DefValueBg",
							"type": "barwithbox",
							"color": normal_color,
							"flash_color": normal_color,
							"box_color": normal_color,
							"width":269,
							"height":23,
							"x":4,
							"y":5 + 25*5,
							"children":
							(
								{"name":"DEF_Value","type":"text","text":"","x":5,"y":-1,"style":("not_pick",),"vertical_align":"center","text_vertical_align":"center",},
							),
						},
						{
							"name":"SlotVIT",
							"type": "barwithbox",
							"color": normal_color,
							"flash_color": normal_color,
							"box_color": normal_color,
							"width":269,
							"height":23,
							"x":4,
							"y":26 + 25*6,
							"children":
							(
								{"name":"HTH_Value","type":"text","text":"","x":5,"y":-1,"style":("not_pick",),"vertical_align":"center","text_vertical_align":"center",},
								{
									"name":"HTH_Minus",
									"type":"button",
									"x":21,
									"y":0,
									"default_image":"interface/controls/common/button_status/minus_n.tga",
									"over_image":"interface/controls/common/button_status/minus_h.tga",
									"down_image":"interface/controls/common/button_status/minus_n.tga",
									"disable_image":"interface/controls/common/button_status/minus_a.tga",
									"horizontal_align":"right",
									"vertical_align":"center",
								},
								{
									"name":"HTH_Plus",
									"type":"button",
									"x":42,
									"y":0,
									"default_image":"interface/controls/common/button_status/plus_n.tga",
									"over_image":"interface/controls/common/button_status/plus_h.tga",
									"down_image":"interface/controls/common/button_status/plus_n.tga",
									"disable_image":"interface/controls/common/button_status/plus_a.tga",
									"horizontal_align":"right",
									"vertical_align":"center",
								},
							),
						},
						{
							"name":"SlotINT",
							"type": "barwithbox",
							"color": normal_color,
							"flash_color": normal_color,
							"box_color": normal_color,
							"width":269,
							"height":23,
							"x":4,
							"y":26 + 25*7,
							"children":
							(
								{"name":"INT_Value","type":"text","text":"","x":5,"y":-1,"style":("not_pick",),"vertical_align":"center","text_vertical_align":"center",},
								{
									"name":"INT_Minus",
									"type":"button",
									"x":21,
									"y":0,
									"default_image":"interface/controls/common/button_status/minus_n.tga",
									"over_image":"interface/controls/common/button_status/minus_h.tga",
									"down_image":"interface/controls/common/button_status/minus_n.tga",
									"disable_image":"interface/controls/common/button_status/minus_a.tga",
									"horizontal_align":"right",
									"vertical_align":"center",
								},
								{
									"name":"INT_Plus",
									"type":"button",
									"x":42,
									"y":0,
									"default_image":"interface/controls/common/button_status/plus_n.tga",
									"over_image":"interface/controls/common/button_status/plus_h.tga",
									"down_image":"interface/controls/common/button_status/plus_n.tga",
									"disable_image":"interface/controls/common/button_status/plus_a.tga",
									"horizontal_align":"right",
									"vertical_align":"center",
								},
							),
						},
						{
							"name":"SlotFOR",
							"type": "barwithbox",
							"color": normal_color,
							"flash_color": normal_color,
							"box_color": normal_color,
							"width":269,
							"height":23,
							"x":4,
							"y":26 + 25*8,
							"children":
							(
								{"name":"STR_Value","type":"text","text":"","x":5,"y":-1,"style":("not_pick",),"vertical_align":"center","text_vertical_align":"center",},
								{
									"name":"STR_Minus",
									"type":"button",
									"x":21,
									"y":0,
									"default_image":"interface/controls/common/button_status/minus_n.tga",
									"over_image":"interface/controls/common/button_status/minus_h.tga",
									"down_image":"interface/controls/common/button_status/minus_n.tga",
									"disable_image":"interface/controls/common/button_status/minus_a.tga",
									"horizontal_align":"right",
									"vertical_align":"center",
								},
								{
									"name":"STR_Plus",
									"type":"button",
									"x":42,
									"y":0,
									"default_image":"interface/controls/common/button_status/plus_n.tga",
									"over_image":"interface/controls/common/button_status/plus_h.tga",
									"down_image":"interface/controls/common/button_status/plus_n.tga",
									"disable_image":"interface/controls/common/button_status/plus_a.tga",
									"horizontal_align":"right",
									"vertical_align":"center",
								},
							),
						},
						{
							"name":"SlotDES",
							"type": "barwithbox",
							"color": normal_color,
							"flash_color": normal_color,
							"box_color": normal_color,
							"width":269,
							"height":23,
							"x":4,
							"y":26 + 25*9,
							"children":
							(
								{"name":"DEX_Value","type":"text","text":"","x":5,"y":-1,"style":("not_pick",),"vertical_align":"center","text_vertical_align":"center",},
								{
									"name":"DEX_Minus",
									"type":"button",
									"x":21,
									"y":0,
									"default_image":"interface/controls/common/button_status/minus_n.tga",
									"over_image":"interface/controls/common/button_status/minus_h.tga",
									"down_image":"interface/controls/common/button_status/minus_n.tga",
									"disable_image":"interface/controls/common/button_status/minus_a.tga",
									"horizontal_align":"right",
									"vertical_align":"center",
								},
								{
									"name":"DEX_Plus",
									"type":"button",
									"x":42,
									"y":0,
									"default_image":"interface/controls/common/button_status/plus_n.tga",
									"over_image":"interface/controls/common/button_status/plus_h.tga",
									"down_image":"interface/controls/common/button_status/plus_n.tga",
									"disable_image":"interface/controls/common/button_status/plus_a.tga",
									"horizontal_align":"right",
									"vertical_align":"center",
								},
							),
						},
						{
							"name":"Status_Plus_Value",
							"type":"text",
							"x":15,
							"y":157,
							"color":text_color,
							"text":"",
						},
					),
				},
### PAGINA DE SKILLS ###### PAGINA DE SKILLS ###### PAGINA DE SKILLS ###### PAGINA DE SKILLS ###### PAGINA DE SKILLS ###
				{
					"name":"Skill_Page",
					"type":"window",
					"width":278,
					"height":282,
					"x":7,
					"y":141,
					"children":
					(
						{
							"name":"HABILIDADES_line",
							"type":"image",
							"image":LINE,
							"x":35,
							"y":10,
							"children":
							(
								{
									"name":"Title_HABILIDADES",
									"type":"text",
									"text":"Habilidades",
									"color":text_color,
									"x":0,
									"y":-5,
									"all_align":"center",
								},
							),
						},
						{ "name":"Active_Skill_Point_Value", "type":"text", "x":15, "y":10 + 90, "text":"Pontos: 99",},
						{ "name":"Master_Skill_Point_Value", "type":"text", "x":15, "y":25 + 90, "text":"Master: [99]",},
						{
							"name":"PASSIVAS_line",
							"type":"image",
							"image":LINE,
							"x":35,
							"y":145,
							"children":
							(
								{
									"name":"Title_PASSIVAS",
									"type":"text",
									"text":"Habilidades Passivas",
									"color":text_color,
									"x":0,
									"y":-5,
									"all_align":"center",
								},
							),
						},
						{
							"name":"slots_skills_images",
							"type":"window",
							"width":246,
							"height":250,
							"x":13.5,
							"y":41,
							"children":
							(
								#Primeira fila
								{"name":"","type":"image","image":SLOT,"x":0,"y":0+1,},
								{"name":"","type":"image","image":SLOT,"x":41,"y":0+1,},
								{"name":"","type":"image","image":SLOT,"x":82,"y":0+1,},
								{"name":"","type":"image","image":SLOT,"x":123,"y":0+1,},
								{"name":"","type":"image","image":SLOT,"x":164,"y":0+1,},
								{"name":"","type":"image","image":SLOT,"x":205,"y":0+1,},
								#Passivas Fila I
								{"name":"","type":"image","image":SLOT,"x":0,"y":155-20,},
								{"name":"","type":"image","image":SLOT,"x":41,"y":155-20,},
								{"name":"","type":"image","image":SLOT,"x":82,"y":155-20,},
								{"name":"","type":"image","image":SLOT,"x":123,"y":155-20,},
								{"name":"","type":"image","image":SLOT,"x":164,"y":155-20,},
								{"name":"","type":"image","image":SLOT,"x":205,"y":155-20,},
								#Passivas Fila II
								{"name":"","type":"image","image":SLOT,"x":0,"y":196-20,},
								{"name":"","type":"image","image":SLOT,"x":41,"y":196-20,},
								{"name":"","type":"image","image":SLOT,"x":82,"y":196-20,},
								{"name":"","type":"image","image":SLOT,"x":123,"y":196-20,},
								{"name":"","type":"image","image":SLOT,"x":164,"y":196-20,},
								{"name":"","type":"image","image":SLOT,"x":205,"y":196-20,},
							),
						},
						{
							"name":"Skill_Active_Slot",
							"type":"slot_elipse",
							"x":5,
							"y":15 + 30,
							"width":278-5,
							"height":223,
							"image":SLOT_BASE,
							"slot":
							(
								{"index": 1, "x": 1+6+5, "y":  1, "width":32, "height":32},
								{"index": 2, "x":42+6+5, "y":  1, "width":32, "height":32},
								{"index": 3, "x":83+6+5, "y":  1, "width":32, "height":32},
								{"index": 4, "x":143-8, "y":  1, "width":32, "height":32},
								{"index": 5, "x":184-8, "y":  1, "width":32, "height":32},
								{"index": 6, "x":225-8, "y":  1, "width":32, "height":32},
							),
						},
						{
							"name":"Skill_ETC_Slot",
							"type":"grid_table_elipse",
							"x":17,
							"y":200-20,
							"start_index":101,
							"x_count":6,
							"y_count":2,
							"x_step":32,
							"y_step":32,
							"x_blank":9,
							"y_blank":9,
							"image":SLOT_BASE,
						},
					),
				},
### PAGINA EMOCOES ###### PAGINA EMOCOES ###### PAGINA EMOCOES ###### PAGINA EMOCOES ###### PAGINA EMOCOES ###### PAGINA EMOCOES ###
				{
					"name":"Emoticon_Page",
					"type":"window",
					"width":278,
					"height":282,
					"x":7,
					"y":141,
					"children":
					(
						{
							"name":"slots_emotions_images",
							"type":"window",
							"width":246,
							"height":282,
							"x":13.5,
							"y":41 - 33,
							"children":
							(
								#Primeira fila
								{"name":"","type":"image","image":SLOT,"x":0,"y":0,},
								{"name":"","type":"image","image":SLOT,"x":41,"y":0,},
								{"name":"","type":"image","image":SLOT,"x":82,"y":0,},
								{"name":"","type":"image","image":SLOT,"x":123,"y":0,},
								{"name":"","type":"image","image":SLOT,"x":164,"y":0,},
								{"name":"","type":"image","image":SLOT,"x":205,"y":0,},
								#Segunda Fila
								{"name":"","type":"image","image":SLOT,"x":0,"y":41,},
								{"name":"","type":"image","image":SLOT,"x":41,"y":41,},
								{"name":"","type":"image","image":SLOT,"x":82,"y":41,},
								{"name":"","type":"image","image":SLOT,"x":123,"y":41,},
								{"name":"","type":"image","image":SLOT,"x":164,"y":41,},
								{"name":"","type":"image","image":SLOT,"x":205,"y":41,},
								#Terceira Fila
								{"name":"","type":"image","image":SLOT,"x":0,"y":82,},
								{"name":"","type":"image","image":SLOT,"x":41,"y":82,},
								{"name":"","type":"image","image":SLOT,"x":82,"y":82,},
								{"name":"","type":"image","image":SLOT,"x":123,"y":82,},
								{"name":"","type":"image","image":SLOT,"x":164,"y":82,},
								{"name":"","type":"image","image":SLOT,"x":205,"y":82,},
								#Quarta Fila
								{"name":"","type":"image","image":SLOT,"x":0,"y":123,},
								{"name":"","type":"image","image":SLOT,"x":41,"y":123,},
								{"name":"","type":"image","image":SLOT,"x":82,"y":123,},
								{"name":"","type":"image","image":SLOT,"x":123,"y":123,},
								{"name":"","type":"image","image":SLOT,"x":164,"y":123,},
								{"name":"","type":"image","image":SLOT,"x":205,"y":123,},
								#Passivas Fila I
								{"name":"","type":"image","image":SLOT,"x":0,"y":155+33,},
								{"name":"","type":"image","image":SLOT,"x":41,"y":155+33,},
								{"name":"","type":"image","image":SLOT,"x":82,"y":155+33,},
								{"name":"","type":"image","image":SLOT,"x":123,"y":155+33,},
								{"name":"","type":"image","image":SLOT,"x":164,"y":155+33,},
								{"name":"","type":"image","image":SLOT,"x":205,"y":155+33,},
								#Passivas Fila II
								{"name":"","type":"image","image":SLOT,"x":0,"y":196+33,},
								{"name":"","type":"image","image":SLOT,"x":41,"y":196+33,},
								{"name":"","type":"image","image":SLOT,"x":82,"y":196+33,},
								{"name":"","type":"image","image":SLOT,"x":123,"y":196+33,},
								{"name":"","type":"image","image":SLOT,"x":164,"y":196+33,},
								{"name":"","type":"image","image":SLOT,"x":205,"y":196+33,},
							),
						},
						{
							"name":"SoloEmotionSlot",
							"type":"grid_table_elipse",
							"x":17,
							"y":45 -33,
							"horizontal_align":"center",
							"start_index":1,
							"x_count":6,
							"y_count":3,
							"x_step":32,
							"y_step":32,
							"x_blank":9,
							"y_blank":9,
							"image":SLOT_BASE,
						},
						{
							"name":"Coletivas_line",
							"type":"image",
							"image":LINE,
							"x":35,
							"y":166,
							"children":
							(
								{
									"name":"Coletivas_PASSIVAS",
									"type":"text",
									"text":"Novas Expressões",
									"color":text_color,
									"x":0,
									"y":-3,
									"all_align":"center",
								},
							),
						},
						{
							"name":"DualEmotionSlot",
							"type":"grid_table_elipse",
							"x":17,
							"y":45 -33 + (3 * 41),
							"start_index":51,
							"x_count":6,
							"y_count":1,
							"x_step":32,
							"y_step":32,
							"x_blank":9,
							"y_blank":9,
							"image":SLOT_BASE,
						},
						{
							"name":"SpecialEmotionSlot",
							"type":"grid_table_elipse",
							"x":17,
							"y":200,
							"start_index":app.SLOT_EMOTION_START,
							"x_count":6,
							"y_count":2,
							"x_step":32,
							"y_step":32,
							"x_blank":9,
							"y_blank":9,
							"image":SLOT_BASE,
						},
					),
				},
### PAGINA QUESTS ###### PAGINA QUESTS ###### PAGINA QUESTS ###### PAGINA QUESTS ###### PAGINA QUESTS ###### PAGINA QUESTS ###### PAGINA QUESTS ###
				{
					"name":"Quest_Page",
					"type":"window",
					"style":("attach",),
					"width":278,
					"height":282,
					"x":7,
					"y":141,
					"children":
					(
						{
							"name":"Quest_Header_00",
							"type":"barwithbox",
							"width":237,"height":37,
							"color":color_quest,
							"box_color":color_quest,
							"flash_color":color_quest,
							"x":8,"y":56-47,
							"children":
							(
								{"name":"Quest_Name_00","type":"text","text":"Quest_Name_00","x":60,"y":1,"color":0xfff8d070,"style":("not_pick",),},
								{"name":"Quest_LastTime_00","type":"text","text":"Quest_LastTime_00","x":60,"y":11,"color":0xffa99999,"style":("not_pick",),},
								{"name":"Quest_LastCount_00","type":"text","text":"Quest_LastCount_00","x":60,"y":21,"color":0xffa99999,"style":("not_pick",),},
							),
						},


						{
							"name":"Quest_Header_01",
							"type":"barwithbox",
							"width":237,"height":37,
							"color":color_quest,
							"box_color":color_quest,
							"flash_color":color_quest,
							"x":8,"y":98-47,
							"children":
							(
								{"name":"Quest_Name_01","type":"text","text":"Quest_Name_01","x":60,"y":1,"color":0xfff8d070,"style":("not_pick",),},
								{"name":"Quest_LastTime_01","type":"text","text":"Quest_LastTime_01","x":60,"y":11,"color":0xffa99999,"style":("not_pick",),},
								{"name":"Quest_LastCount_01","type":"text","text":"Quest_LastCount_01","x":60,"y":21,"color":0xffa99999,"style":("not_pick",),},
							),
						},

						{
							"name":"Quest_Header_02",
							"type":"barwithbox",
							"width":237,"height":37,
							"color":color_quest,
							"box_color":color_quest,
							"flash_color":color_quest,
							"x":8,"y":140-47,
							"children":
							(
								{"name":"Quest_Name_02","type":"text","text":"Quest_Name_02","x":60,"y":1,"color":0xfff8d070,"style":("not_pick",),},
								{"name":"Quest_LastTime_02","type":"text","text":"Quest_LastTime_02","x":60,"y":11,"color":0xffa99999,"style":("not_pick",),},
								{"name":"Quest_LastCount_02","type":"text","text":"Quest_LastCount_02","x":60,"y":21,"color":0xffa99999,"style":("not_pick",),},
							),
						},

						{
							"name":"Quest_Header_03",
							"type":"barwithbox",
							"width":237,"height":37,
							"color":color_quest,
							"box_color":color_quest,
							"flash_color":color_quest,
							"x":8,"y":182-47,
							"children":
							(
								{"name":"Quest_Name_03","type":"text","text":"Quest_Name_03","x":60,"y":1,"color":0xfff8d070,"style":("not_pick",),},
								{"name":"Quest_LastTime_03","type":"text","text":"Quest_LastTime_03","x":60,"y":11,"color":0xffa99999,"style":("not_pick",),},
								{"name":"Quest_LastCount_03","type":"text","text":"Quest_LastCount_03","x":60,"y":21,"color":0xffa99999,"style":("not_pick",),},
							),
						},

						{
							"name":"Quest_Header_04",
							"type":"barwithbox",
							"width":237,"height":37,
							"color":color_quest,
							"box_color":color_quest,
							"flash_color":color_quest,
							"x":8,"y":224-47,
							"children":
							(
								{"name":"Quest_Name_04","type":"text","text":"Quest_Name_04","x":60,"y":1,"color":0xfff8d070,"style":("not_pick",),},
								{"name":"Quest_LastTime_04","type":"text","text":"Quest_LastTime_04","x":60,"y":11,"color":0xffa99999,"style":("not_pick",),},
								{"name":"Quest_LastCount_04","type":"text","text":"Quest_LastCount_04","x":60,"y":21,"color":0xffa99999,"style":("not_pick",),},
							),
						},

						{
							"name":"Quest_Header_05",
							"type":"barwithbox",
							"width":237,"height":37,
							"color":color_quest,
							"box_color":color_quest,
							"flash_color":color_quest,
							"x":8,"y":219,
							"children":
							(
								{"name":"Quest_Name_05","type":"text","text":"Quest_Name_05","x":60,"y":1,"color":0xfff8d070,"style":("not_pick",),},
								{"name":"Quest_LastTime_05","type":"text","text":"Quest_LastTime_05","x":60,"y":11,"color":0xffa99999,"style":("not_pick",),},
								{"name":"Quest_LastCount_05","type":"text","text":"Quest_LastCount_05","x":60,"y":21,"color":0xffa99999,"style":("not_pick",),},
							),
						},

						{
							"name":"Quest_Slot",
							"type":"grid_table_elipse",
							"x":15,
							"y":60-47,
							"start_index":0,
							"x_count":1,
							"y_count":6,
							"x_step":32,
							"y_step":32,
							"y_blank":10,
							"image":SLOT_BASE,
						},
						{
							"name":"Quest_ScrollBar",
							"type":"new_scrollbar",
							"x":20,
							"y":10,
							"size":260,
							"horizontal_align":"right",
							"children":
							(
								{
									"name":"",
									"type":"verticalseparator",
									"height":277,
									"x":-6,
									"y":-9,
								},
							),
						},
					),
				},
### PAGINA DE BONUS ###### PAGINA DE BONUS ###### PAGINA DE BONUS ###### PAGINA DE BONUS ###### PAGINA DE BONUS ###### PAGINA DE BONUS ###
				{
					"name":"Bonus_Page",
					"type":"window",
					"width":278,
					"height":282,
					"x":7,
					"y":141,
					"children":
					(
						{
							"name":"Offensive_Bonus",
							"type":"window",
							"width":278,
							"height":32,
							"x":0,
							"y":0,
							"children":
							(
								{
									"name":"Offensive_Bonus_Separator",
									"type":"horizontalseparator",
									"width":278,
									"x":0,
									"y":-1,
								},
								{
									"name":"Offensive_Bonus_Image",
									"type":"barwithbox",
									"width":277,"height":32,
									"color":normal_color,
									"box_color":normal_color,
									"flash_color":hover_color2,
									"x":1,"y":2,
								},
								{"name":"Offensive_Bonus_Title","type":"text","text":"Bônus Ofensivos","x":8,"y":9,"style":("not_pick",),"fontname":"Verdana:16b"},
								{
									"name": "Offensive_Bonus_Finder",
									"type": "barwithbox",
									"x":247,"y":4,
									"width":29, "height":28,
									"color": normal_color,
									"flash_color": hover_color,
									"box_color": box_color,
									"children":
									(
										{"name":"Offensive_Bonus_Finder_Desc","type":"text","text":"Filtro...","x":5,"y":-2,"vertical_align":"center","hide":1,"text_vertical_align":"center","style":("not_pick",),},
										{
											"name":"Offensive_Bonus_Finder_EditLine",
											"type":"editline",
											"style":("not_pick",),
											"x":5,
											"y":13,
											"horizontal_align":"left",
											"text_horizontal_align":"left",
											"text_vertical_align":"center",
											"vertical_align":"center",
											"width":110,
											"height":28,
											"input_limit":10,
											"hide":1,
										},
									),
								},
								{
									"name":"Offensive_Bonus_Finder_Image",
									"type":"image",
									"style":("not_pick",),
									"image":"interface/controls/special/character/finder.tga",
									"x":245+9,"y":10,
								},
							),
						},
						{
							"name":"Defensive_Bonus",
							"type":"window",
							"width":278,
							"height":32,
							"x":0,
							"y":35,
							"children":
							(
								{
									"name":"Defensive_Bonus_Separator",
									"type":"horizontalseparator",
									"width":279,
									"x":0,
									"y":-1,
								},
								{
									"name":"Defensive_Bonus_Image",
									"type":"barwithbox",
									"width":277,"height":32,
									"color":normal_color,
									"box_color":normal_color,
									"flash_color":hover_color2,
									"x":1,"y":2,
								},
								{"name":"Defensive_Bonus_Title","type":"text","text":"Bônus Defensivos","x":8,"y":9,"style":("not_pick",), "fontname":"Verdana:16b"},
								{
									"name": "Defensive_Bonus_Finder",
									"type": "barwithbox",
									"x":247,"y":4,
									"width":29, "height":28,
									"color": normal_color,
									"flash_color": hover_color,
									"box_color": box_color,
									"children":
									(
										{"name":"Defensive_Bonus_Finder_Desc","type":"text","text":"Filtro...","x":5,"y":-2,"vertical_align":"center","hide":1,"text_vertical_align":"center","style":("not_pick",),},
										{
											"name": "Defensive_Bonus_Finder_EditLine",
											"type": "editline",
											"style":("not_pick",),
											"x":5,
											"y":13,
											"horizontal_align":"left",
											"text_horizontal_align":"left",
											"text_vertical_align":"center",
											"vertical_align":"center",
											"width":110,
											"height":28,
											"input_limit":10,
											"hide":1,
										},
									),
								},
								{
									"name":"Defensive_Bonus_Finder_Image",
									"type":"image",
									"style":("not_pick",),
									"image":"interface/controls/special/character/finder.tga",
									"x":245+9,"y":10,
								},
							),
						},####
						{
							"name":"PVM_Bonus",
							"type":"window",
							"width":278,
							"height":32,
							"x":0,
							"y":35*2,
							"children":
							(
								{
									"name":"PVM_Bonus_Separator",
									"type":"horizontalseparator",
									"width":278,
									"x":0,
									"y":-1,
								},
								{
									"name":"PVM_Bonus_Image",
									"type":"barwithbox",
									"width":277,"height":32,
									"color":normal_color,
									"box_color":normal_color,
									"flash_color":hover_color2,
									"x":1,"y":2,
								},
								{"name":"PVM_Bonus_Title","type":"text","text":"Bônus PVM","x":8,"y":9,"style":("not_pick",),"fontname":"Verdana:16b"},
								{
									"name": "PVM_Bonus_Finder",
									"type": "barwithbox",
									"x":247,"y":4,
									"width":29, "height":28,
									"color": normal_color,
									"flash_color": hover_color,
									"box_color": box_color,
									"children":
									(
										{"name":"PVM_Bonus_Finder_Desc","type":"text","text":"Filtro...","x":5,"y":-2,"vertical_align":"center","hide":1,"text_vertical_align":"center","style":("not_pick",),},
										{
											"name": "PVM_Bonus_Finder_EditLine",
											"type": "editline",
											"style":("not_pick",),
											"x":5,
											"y":13,
											"horizontal_align":"left",
											"text_horizontal_align":"left",
											"text_vertical_align":"center",
											"vertical_align":"center",
											
											"width":110,
											"height":28,
											"input_limit":10,
											"hide":1,
										},
									),
								},
								{
									"name":"PVM_Bonus_Finder_Image",
									"type":"image",
									"style":("not_pick",),
									"image":"interface/controls/special/character/finder.tga",
									"x":245+9,"y":10,
								},
							),
						},
######################################################################################################################
						{
							"name":"Offensive_Bonus_Window",
							"type":"window",
							"width":278,
							"height":175,
							"x":0,
							"y":35*0 + 32,
							"hide":1,
							"children":
							(
								{"name":"Offensive_0","type":"text","text":"","x":13, "y":5+19*0,},
								{"name":"Offensive_1","type":"text","text":"","x":13, "y":5+19*1,},
								{"name":"Offensive_2","type":"text","text":"","x":13, "y":5+19*2,},
								{"name":"Offensive_3","type":"text","text":"","x":13, "y":5+19*3,},
								{"name":"Offensive_4","type":"text","text":"","x":13, "y":5+19*4,},
								{"name":"Offensive_5","type":"text","text":"","x":13, "y":5+19*5,},
								{"name":"Offensive_6","type":"text","text":"","x":13, "y":5+19*6,},
								{"name":"Offensive_7","type":"text","text":"","x":13, "y":5+19*7,},
								{"name":"Offensive_8","type":"text","text":"","x":13, "y":5+19*8,},
								{
									"name":"Offensive_ScrollBar",
									"type":"new_scrollbar",
									"x":21,
									"y":1,
									"size":169,
									"vertical_align":"center",
									"horizontal_align":"right",
								},
							),
						},
						{
							"name":"Defensive_Bonus_Window",
							"type":"window",
							"width":278,
							"height":175,
							"x":0,
							"y":35*1 + 32,
							"hide":1,
							"children":
							(
								{"name":"Defensive_0","type":"text","text":"","x":13, "y":5+19*0,},
								{"name":"Defensive_1","type":"text","text":"","x":13, "y":5+19*1,},
								{"name":"Defensive_2","type":"text","text":"","x":13, "y":5+19*2,},
								{"name":"Defensive_3","type":"text","text":"","x":13, "y":5+19*3,},
								{"name":"Defensive_4","type":"text","text":"","x":13, "y":5+19*4,},
								{"name":"Defensive_5","type":"text","text":"","x":13, "y":5+19*5,},
								{"name":"Defensive_6","type":"text","text":"","x":13, "y":5+19*6,},
								{"name":"Defensive_7","type":"text","text":"","x":13, "y":5+19*7,},
								{"name":"Defensive_8","type":"text","text":"","x":13, "y":5+19*8,},
								{
									"name":"Defensive_ScrollBar",
									"type":"new_scrollbar",
									"x":21,
									"y":1,
									"size":169,
									"vertical_align":"center",
									"horizontal_align":"right",
								},
							),
						},
						{
							"name":"PVM_Bonus_Window",
							"type":"window",
							"width":278,
							"height":175,
							"x":0,
							"y":35*2 + 32,
							"hide":1,
							"children":
							(
								{"name":"PVM_0","type":"text","text":"","x":13, "y":5+19*0,},
								{"name":"PVM_1","type":"text","text":"","x":13, "y":5+19*1,},
								{"name":"PVM_2","type":"text","text":"","x":13, "y":5+19*2,},
								{"name":"PVM_3","type":"text","text":"","x":13, "y":5+19*3,},
								{"name":"PVM_4","type":"text","text":"","x":13, "y":5+19*4,},
								{"name":"PVM_5","type":"text","text":"","x":13, "y":5+19*5,},
								{"name":"PVM_6","type":"text","text":"","x":13, "y":5+19*6,},
								{"name":"PVM_7","type":"text","text":"","x":13, "y":5+19*7,},
								{"name":"PVM_8","type":"text","text":"","x":13, "y":5+19*8,},
								{
									"name":"PVM_ScrollBar",
									"type":"new_scrollbar",
									"x":21,
									"y":1,
									"size":169,
									"vertical_align":"center",
									"horizontal_align":"right",
								},
							),
						},
					),
				},
### RANKING PAGE ###### RANKING PAGE ###### RANKING PAGE ###### RANKING PAGE ###### RANKING PAGE ###### RANKING PAGE ###
				{
					"name":"Ranking_Page",
					"type":"window",
					"style":("attach",),
					"width":278,
					"height":282,
					"x":7,
					"y":141,
					"children":
					(
						{
							"name":"Ranking_ScrollBar",
							"type":"new_scrollbar",
							"x":20,
							"y":10,
							"size":260,
							"horizontal_align":"right",
							"children":
							(
								{
									"name":"",
									"type":"verticalseparator",
									"height":277,
									"x":-6,
									"y":-9,
								},
							),
						},
						{"name":"","type":"bar","color":normal_color,"x":1,"y":2+18*0,"height":18,"width":251},
						{"name":"","type":"bar","color":hover_color,"x":1,"y":2+18*1,"height":18,"width":251},
						{"name":"","type":"bar","color":normal_color,"x":1,"y":2+18*2,"height":18,"width":251},
						{"name":"","type":"bar","color":hover_color,"x":1,"y":2+18*3,"height":18,"width":251},
						{"name":"","type":"bar","color":normal_color,"x":1,"y":2+18*4,"height":18,"width":251},
						{"name":"","type":"bar","color":hover_color,"x":1,"y":2+18*5,"height":18,"width":251},
						{"name":"","type":"bar","color":normal_color,"x":1,"y":2+18*6,"height":18,"width":251},
						{"name":"","type":"bar","color":hover_color,"x":1,"y":2+18*7,"height":18,"width":251},
						{"name":"","type":"bar","color":normal_color,"x":1,"y":2+18*8,"height":18,"width":251},
						{"name":"","type":"bar","color":hover_color,"x":1,"y":2+18*9,"height":18,"width":251},
						{"name":"","type":"bar","color":normal_color,"x":1,"y":2+18*10,"height":18,"width":251},
						{"name":"","type":"bar","color":hover_color,"x":1,"y":2+18*11,"height":18,"width":251},
						{"name":"","type":"bar","color":normal_color,"x":1,"y":2+18*12,"height":18,"width":251},
						{"name":"","type":"bar","color":hover_color,"x":1,"y":2+18*13,"height":18,"width":251},
						{"name":"","type":"bar","color":normal_color,"x":1,"y":2+18*14,"height":18+5,"width":251},

						{"name":"RK_0","type":"text","text":"","x":5, "y":4+18*0,},
						{"name":"RK_1","type":"text","text":"","x":5, "y":4+18*1,},
						{"name":"RK_2","type":"text","text":"","x":5, "y":4+18*2,},
						{"name":"RK_3","type":"text","text":"","x":5, "y":4+18*3,},
						{"name":"RK_4","type":"text","text":"","x":5, "y":4+18*4,},
						{"name":"RK_5","type":"text","text":"","x":5, "y":4+18*5,},
						{"name":"RK_6","type":"text","text":"","x":5, "y":4+18*6,},
						{"name":"RK_7","type":"text","text":"","x":5, "y":4+18*7,},
						{"name":"RK_8","type":"text","text":"","x":5, "y":4+18*8,},
						{"name":"RK_9","type":"text","text":"","x":5, "y":4+18*9,},
						{"name":"RK_10","type":"text","text":"","x":5, "y":4+18*10,},
						{"name":"RK_11","type":"text","text":"","x":5, "y":4+18*11,},
						{"name":"RK_12","type":"text","text":"","x":5, "y":4+18*12,},
						{"name":"RK_13","type":"text","text":"","x":5, "y":4+18*13,},
						{"name":"RK_14","type":"text","text":"","x":5, "y":4+18*14,},

						{"name":"PRK_0","type":"text","text":"","x":145, "y":4+18*0,},
						{"name":"PRK_1","type":"text","text":"","x":145, "y":4+18*1,},
						{"name":"PRK_2","type":"text","text":"","x":145, "y":4+18*2,},
						{"name":"PRK_3","type":"text","text":"","x":145, "y":4+18*3,},
						{"name":"PRK_4","type":"text","text":"","x":145, "y":4+18*4,},
						{"name":"PRK_5","type":"text","text":"","x":145, "y":4+18*5,},
						{"name":"PRK_6","type":"text","text":"","x":145, "y":4+18*6,},
						{"name":"PRK_7","type":"text","text":"","x":145, "y":4+18*7,},
						{"name":"PRK_8","type":"text","text":"","x":145, "y":4+18*8,},
						{"name":"PRK_9","type":"text","text":"","x":145, "y":4+18*9,},
						{"name":"PRK_10","type":"text","text":"","x":145, "y":4+18*10,},
						{"name":"PRK_11","type":"text","text":"","x":145, "y":4+18*11,},
						{"name":"PRK_12","type":"text","text":"","x":145, "y":4+18*12,},
						{"name":"PRK_13","type":"text","text":"","x":145, "y":4+18*13,},
						{"name":"PRK_14","type":"text","text":"","x":145, "y":4+18*14,},
					),
				},
##########################################################################################################################
			),
		},
	),
}
