#favor manter essa linha
import uiscriptlocale

window = {
	"name":"AttachStoneDialog",
	"style":("movable", "float",),
	"x":0,
	"y":0,
	"width":0,
	"height":0,
	"children":
	(
		{
			"name":"Board",
			"type":"new_board_with_titlebar",
			"style":("attach",),
			"x":0,
			"y":0,
			"title":uiscriptlocale.ATTACH_METIN_TITLE,
			"width":0,
			"height":0,
			"children":
			(
				{
					"name":"MetinSlot",
					"type":"image",
					"x":0,
					"y":5,
					"horizontal_align":"center",
					"vertical_align":"center",
					"image":"interface/controls/special/refine/slot.tga",
					"children":
					(
						{
							"name":"MetinImage",
							"type":"image",
							"x":0,
							"y":0,
							"horizontal_align":"center",
							"vertical_align":"center",
							"image":"interface/controls/common/slot_ellipse/slot_vazio.tga",
						},
					),
				},
				{
					"name":"Question",
					"type":"text",
					"text":"Deseja inserir a Jóia?",
					"horizontal_align":"center",
					"vertical_align":"bottom",
					"text_horizontal_align":"center",
					"x":0,
					"y":63,
				},
				{
					"name":"horizontalseparator",
					"type":"horizontalseparator",
					"width":1,
					"x":7,
					"y":69,
					"vertical_align":"bottom",
				},
				{
					"name":"AcceptButton",
					"type":"redbutton",
					"x":-35,
					"y":43,
					"width":60,
					"text":"Sim",
					"horizontal_align":"center",
					"vertical_align":"bottom",
				},
				{
					"name":"CancelButton",
					"type":"redbutton",
					"x":35,
					"y":43,
					"width":60,
					"text":"Não",
					"horizontal_align":"center",
					"vertical_align":"bottom",
				},
			),
		},
	),
}